@startuml
allowmixing
scale 3

package "Frontend (JS)" as PFrontend {
  agent "Form Submition" as AFormSubmition
  agent "Document Ready" as ADomReady

  object AccessModule {
    ~initialize()
    -login()
    -report()
  }

  object UsersModule {
    ~initialize()
    -update()
    -refresh()
  }

  ADomReady -- AFormSubmition
  ADomReady --> AccessModule::initialize
  AFormSubmition --> AccessModule::login
  AccessModule::login --> UsersModule::initialize
}

package "Backend (PHP)" as PBackend {
  agent "index.php" as ABackendIndex

  object Router {
    ~handleRoute()
    -loginRoute()
  }

  object Users {
    ~update()
    ~create()
  }

  object Validation {
    ~email($email)
  }

  ABackendIndex --> Router
  Router::loginRoute --> Validation
  Validation --> Router
}

AccessModule::login --> ABackendIndex : Login
ABackendIndex --> AccessModule::login
UsersModule::update --> ABackendIndex : Update

@enduml
